name: Deploy to EKS  
  
on:  
  push:  
    branches:  
      - main  
  
jobs:  
  deploy:  
    runs-on: ubuntu-latest  
  
    steps:  
    - name: Checkout code  
      uses: actions/checkout@v2  
  
    - name: Configure AWS credentials  
      uses: aws-actions/configure-aws-credentials@v1  
      with:  
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  
        aws-region: <ap-southeast-1> # 替换为您的 AWS 区域  
  
    - name: Configure kubectl  
      uses: azure/kubectl@v1  
      with:  
        version: 'v1.18.8' # 替换为您的 kubectl 版本  
  
    - name: Deploy Nginx  
      run: |  
            cat <<EOF | kubectl apply -f -  
            apiVersion: apps/v1  
            kind: Deployment  
            metadata:  
              name: nginx  
            spec:  
              selector:  
                matchLabels:  
                  app: nginx  
              template:  
                metadata:  
                  labels:  
                    app: nginx  
                spec:  
                  containers:  
                  - name: nginx  
                    image: nginx  
                    ports:  
                    - containerPort: 80  
                    volumeMounts:  
                    - name: config  
                      mountPath: /usr/share/nginx/html  
                      readOnly: true  
                  volumes:  
                  - name: config  
                    configMap:  
                      name: nginx-config  
            ---  
            apiVersion: v1  
            kind: Service  
            metadata:  
              name: nginx  
            spec:  
              selector:  
                app: nginx  
              ports:  
              - protocol: TCP  
                port: 80  
                targetPort: 80  
                name: http  
            ---  
            apiVersion: v1  
            kind: ConfigMap  
            metadata:  
              name: nginx-config  
            data:  
              index.html: |  
                <!DOCTYPE html>  
                <html>  
                <head>  
                  <title>Hello</title>  
                </head>  
                <body>  
                  <h1>Hello</h1>  
                </body>  
                </html>  
            EOF   
